website/auth.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
import flask_login, re
from flask_login import login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from .models import User, Influencer, Campaign, Ad_request
from markupsafe import Markup 

auth=Blueprint("auth",__name__)

@auth.route("/", methods=["GET", "POST"])
@auth.route('/signup', methods=['GET','POST'])
def signup():
    if request.method=='POST':
        user_name=request.form['usrname']
        name=request.form['name']
        mailid=request.form['mail']
        pwd1=request.form['p1']
        pwd2=request.form['p2']
        role=request.form['role']

        email_already_exists=User.query.filter_by(mail=mailid).first()
        user_already_exists=User.query.filter_by(usr_name=user_name).first()

        gen_mail= r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'

        def isValid(mail):
            if re.fullmatch(gen_mail, mail):
                return "Valid Email"
            else:
                return "Invalid Email"
        
        if isValid(mailid)=='Invalid Email':
            flash('Invalid Email Adress', category='danger')
        elif email_already_exists:
            flash(Markup('Email already in use. <a href="/login" class="alert-link">Login</a> instead.'), category='warning')
        elif user_already_exists:
            flash('Username already exist. Choose a different username.', category='danger')
        elif pwd2!=pwd1:
            flash("Confirm password does not match. Renter the password", category='danger')
        else:
            usr=User(usr_name=user_name, name=name,mail=mailid,password=generate_password_hash(pwd1),role=role)
            db.session.add(usr)
            db.session.commit()
            if role=='Influencer':
                new_influencer = Influencer(
                    user_id=usr.usr_id,  # Reference to the user
                    name=name,
                    mail_id=mailid)
                db.session.add(new_influencer)
                db.session.commit()
            flash('User Created. Login to Proceed', 'success')
            return redirect(url_for("auth.login"))
    return render_template('signup.html', message=0)


# # ---------------------------------- Login --------------------------------------------

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method== 'POST':
        user_name = request.form['usrname']
        pwd = request.form['password']

        if not user_name:
            flash('Please enter username', category='warning')
        elif not pwd:
            flash('Enter the password', category='warning')
        else:
            user = User.query.filter_by(usr_name=user_name).first()
            if user and check_password_hash(user.password, pwd):
                login_user(user)
                if user.role=="Sponsor":
                    return redirect(url_for("views.sponsor_home"))
                elif user.role=="Influencer":
                    influ= Influencer.query.filter_by(user_id=user.usr_id).first()
                    if influ and influ.is_flag:
                        flash("You have been Flagged. Can't login", category="danger")
                        return redirect(url_for('auth.login'))
                    return redirect(url_for("views.influ_home"))
                else:
                    return redirect(url_for("views.admin_home"))
            elif user:
                flash('Invalid Password', category='danger')
            else:
                flash(Markup('You haven\'t registered yet. <a href="/signup" class="alert-link">Sign Up</a> instead'), category='warning')
    return render_template('login.html')


# # ------------------------ LOGOUT -----------------------------------------------------

@auth.route("/logout")
@flask_login.login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

website/views.py
from flask import Blueprint, render_template, url_for, redirect, request, flash, make_response
import flask_login, io
from flask_login import current_user
from . import db
from matplotlib.pyplot import Figure
from .models import User, Influencer, Campaign, Ad_request
import datetime as dt


views=Blueprint("views",__name__)

# --------------------------------------------ADMIN Routes------------------------------------
@views.route("/admin home")
@flask_login.login_required
def admin_home():
    return render_template("admin_home.html",admin_name=current_user.name)


@views.route("/plot_users/plot.png")
@flask_login.login_required
def plot_users():
    roles=['Sponsor','Influencer']
    user_data=[db.session.query(User).filter_by(role=role).count() for role in roles]

    fig1 = Figure()
    ax = fig1.subplots()
    ax.bar(roles, user_data, color=['gold','orange'])
    ax.set_xlabel('Role')
    ax.set_ylabel('Number of Users')
    ax.set_title('Number of Users by Role')
    user_output1 = io.BytesIO()
    fig1.savefig(user_output1, format='png')
    user_output1.seek(0)
    return make_response(user_output1.getvalue(), 200, {'Content-Type': 'image/png'})


@views.route("/plot_campaigns/plot.png")
@flask_login.login_required
def plot_campaigns():
    visibility=['Public','Private']
    cpg_data=[db.session.query(Campaign).filter_by(visibility=visible).count() for visible in visibility]
    fig2 = Figure()
    ax = fig2.subplots()
    ax.bar(visibility, cpg_data, color=['magenta','red'])
    ax.set_xlabel('Campaign Visibility')
    ax.set_ylabel('Campaign')
    ax.set_title('Count')
    user_output2 = io.BytesIO()
    fig2.savefig(user_output2, format='png')
    user_output2.seek(0)
    return make_response(user_output2.getvalue(), 200, {'Content-Type': 'image/png'})

@views.route("/flag_user/<int:influ_id>",methods=['POST'])
@flask_login.login_required
def flag_influencer(influ_id):
    influ=Influencer.query.get_or_404(influ_id)
    influ.is_flag= not influ.is_flag
    db.session.commit()
    return redirect(url_for('views.show_influencers'))


@views.route("/admin_campaigns")
@flask_login.login_required
def show_campaigns():
    campaigns= Campaign.query.all()
    return render_template("admin_campaigns.html",campaigns=campaigns, admin_name=current_user.name)


@views.route("/show_influencers")
@flask_login.login_required
def show_influencers():
    influencers=Influencer.query.all()
    return render_template("admin_influencers.html",influencers=influencers,admin_name=current_user.name)


# --------------------------------------------Influencer Routes-------------------------------

@views.route("/influencer home")
@flask_login.login_required
def influ_home():
    new_influencer =Influencer.query.filter_by(user_id=current_user.usr_id).first()
    if new_influencer:
        if new_influencer.category is None and new_influencer.niche is None and new_influencer.reach is None:
            flash("Please update your profile before accepting requests", "warning")
            return redirect(url_for("views.edit_influ_profile",influencer_id=new_influencer.influencer_id))
    campaigns=Campaign.query.all()
    my_requests=Ad_request.query.filter_by(influencer_id=new_influencer.influencer_id).all()
    return render_template("influ_home.html",campaigns=campaigns,requests=my_requests,influ_name=current_user.name)


@views.route("/influencer profile")
@flask_login.login_required
def influ_profile():
    influencer = Influencer.query.filter_by(user_id=current_user.usr_id).first()
    return render_template('influ_profile.html',influencer=influencer, influ_name=current_user.name)


@views.route("/edit_influencer_profile/<int:influencer_id>", methods=['GET', 'POST'])
@flask_login.login_required
def edit_influ_profile(influencer_id):
    influencer = Influencer.query.get_or_404(influencer_id)
    if request.method == 'POST':
        # Get the updated data from the form
        influencer.category = request.form.get('category')
        influencer.niche = request.form.get('niche')
        influencer.reach = request.form.get('reach')
        # Save changes to the database  
        db.session.commit()
        return redirect(url_for('views.influ_home'))
    return render_template('edit_influ_profile.html',influencer=influencer ,influ_name=current_user.name)


@views.route("/accept_request/<int:ad_id>", methods=['POST'])
@flask_login.login_required
def accept_request(ad_id):
    ad_request=Ad_request.query.get_or_404(ad_id)
    ad_request.status='Accepted'
    db.session.commit()
    flash("Request accepted!",category='success')
    return redirect(url_for('views.influ_home'))


@views.route("/reject_request/<int:ad_id>", methods=['POST'])
@flask_login.login_required
def reject_request(ad_id):
    ad_request=Ad_request.query.get_or_404(ad_id)
    ad_request.status='Rejected'
    db.session.commit()
    flash("Request rejected!",category='danger')
    return redirect(url_for('views.influ_home'))


@views.route('/search_campaigns',methods=['GET'])
@flask_login.login_required
def search_campaigns():
    query=  request.args.get('query','')
    new_influencer =Influencer.query.filter_by(user_id=current_user.usr_id).first()
    if query:
        campaign_search=f'%{query}%'
        campaign=Campaign.query.filter(
            (Campaign.campaign_name.ilike(campaign_search))|(Campaign.budget.ilike(campaign_search))|
            (Campaign.visibility.ilike(campaign_search))).all()
        my_requests=Ad_request.query.filter_by(influencer_id=new_influencer.influencer_id).all()
        return render_template('influ_home.html',campaigns=campaign, influ_name=current_user.name,requests=my_requests)
    else:
        return redirect(url_for('views.influ_home.html'))


# --------------------------------------------SPONSOR Routes----------------------------------

@views.route("/sponsor home")
@flask_login.login_required
def sponsor_home():
    campaigns=Campaign.query.all()
    influencers=Influencer.query.all()
    return render_template("sponsor_home.html",campaigns=campaigns, influencers=influencers, sponsor_name=current_user.name)


@views.route("/create_campaign", methods=['GET','POST'])
@flask_login.login_required
def create_campaign():
    if request.method=="POST":
        campaign_name=request.form['campaign_name']
        description=request.form['description']
        start_date=request.form['start_date']
        end_date=request.form['end_date']
        budget=request.form['budget']
        try:
            # Convert string dates to date objects
            start_date = dt.datetime.strptime(start_date, '%Y-%m-%d').date()
            end_date = dt.datetime.strptime(end_date, '%Y-%m-%d').date()
        except ValueError:
            flash('Invalid date format. Please use YYYY-MM-DD.', 'danger')
            return render_template("create_campaign.html")

        try:
            # Convert budget to integer
            budget = int(request.form['budget'])
        except ValueError:
            flash('Budget must be a number.', 'danger')
            return render_template("create_campaign.html")
        visibility=request.form['visibility']
        cpg=Campaign(campaign_name=campaign_name,description=description,start_date=start_date,
                     end_date=end_date, budget=budget,
                     visibility=visibility, user_id=current_user.usr_id)
        db.session.add(cpg)
        db.session.commit()
        return redirect(url_for("views.sponsor_home"))
    return render_template("create_campaign.html",sponsor_name=current_user.name)


@views.route("/manage_my_campaigns")
@flask_login.login_required
def manage_campaigns():
    # return all the campaigns created by the current user
    my_campaigns=Campaign.query.filter_by(user_id=current_user.usr_id).all()
    return render_template('my_campaigns.html',campaigns=my_campaigns,sponsor_name=current_user.name)


@views.route("/edit_campaign/<int:campaign_id>",methods=['GET','POST'])
@flask_login.login_required
def edit_campaign(campaign_id):
    campaign=Campaign.query.get_or_404(campaign_id)

    #checking if the campaign belongs to current user or not
    if campaign.user_id!=current_user.usr_id:
        flash("You are not the author of this campaign","danger")
        return redirect(url_for("views.manage_campaigns"))
    if request.method=='POST':
        campaign.campaign_name=request.form['campaign_name']
        campaign.description=request.form['description']
        campaign.start_date = dt.datetime.strptime(request.form['start_date'], '%Y-%m-%d').date()
        campaign.end_date = dt.datetime.strptime(request.form['end_date'], '%Y-%m-%d').date()
        campaign.budget = int(request.form['budget'])
        campaign.visibility = request.form['visibility']
        db.session.commit()
        return redirect(url_for("views.manage_campaigns"))
    return render_template("edit_campaigns.html",campaign=campaign,sponsor_name=current_user.name)


@views.route("/delete_campaign/<int:campaign_id>",methods=['GET','POST'])
@flask_login.login_required
def delete_campaign(campaign_id):
    campaign=Campaign.query.get_or_404(campaign_id)
    #checking if the campaign belongs to current user or not
    if campaign.user_id!=current_user.usr_id:
        flash("You are not the author of this campaign","danger")
    db.session.delete(campaign)
    db.session.commit()
    return redirect(url_for('views.manage_campaigns'))


@views.route('/search',methods=['GET'])
@flask_login.login_required
def search_influencers():
    query=  request.args.get('query','')
    if query:
        influ_search=f'%{query}%'
        influencers=Influencer.query.filter(
            (Influencer.name.ilike(influ_search))|(Influencer.category.ilike(influ_search))|
            (Influencer.niche.ilike(influ_search))|(Influencer.reach.ilike(influ_search))).all()
        campaigns=Campaign.query.all()

website/templates/admin_base.html
{% extends "base.html" %}
{% block title %}Sponsor Page{% endblock %}
{% block side_bar_options %}
<h3>Hello {{admin_name}}</h3>
<br>
<br>
<br>
<nav class="navbar bg-body">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('views.admin_home') }}">Home</a>    
    </div>
</nav>
<br>
<br>
<nav class="navbar bg-body">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('views.show_campaigns') }}">Campaigns</a>    
    </div>
</nav>
<br>
<br>
<nav class="navbar bg-body">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('views.show_influencers') }}">Influencers</a>    
    </div>
</nav>
<br>
{% endblock %}

{% block content %}

{% endblock %}

website/templates/admin_campaigns.html
{% extends "admin_base.html" %}
{% block content %}
    <h4>Registered Campaigns</h4>
    <br>
            <br>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Campaign Name</th>
                            <th>Description</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Budget Allocated</th>
                            <th>Visibility</th>
                        </tr>            
                    </thead>
                    <tbody>
                    {% for cpg in campaigns %}
                        <tr>
                            <td>{{ cpg.campaign_name }}</td>
                            <td>{{ cpg.description }}</td>
                            <td>{{ cpg.start_date }}</td>
                            <td>{{ cpg.end_date }}</td>
                            <td>{{ cpg.budget }}</td>
                            <td>{{ cpg.visibility }}</td>
                        </tr>
                    {% else %}
                    <tr>
                        <td colspan="7">No campaigns found</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>  
{% endblock %}

website/templates/admin_influencers.html
{% extends "admin_base.html" %}
{% block content %}
    <h4>Shows the list of influencers registered, and can flag them</h4>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Niche</th>
                    <th>Reach</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for inf in influencers %}
                <tr>
                    <td>{{ inf.name }}</td>
                    <td>{{ inf.category }}</td>
                    <td>{{ inf.niche }}</td>
                    <td>{{ inf.reach }}</td>
                    <td>
                        <form action="{{ url_for('views.flag_influencer', influ_id=inf.influencer_id) }}"
                         method="post" style="display:inline;">
                            {% if inf.is_flag %}
                            <button type="submit" class="btn btn-danger btn-sm">Un-Flag</button>
                            {% else %}
                            <button type="submit" class="btn btn-danger btn-sm">Flag</button>
                            {% endif %}
                        </form>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="5">No Influencers found</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> {% block title %}Influencer home page {% endblock %}</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">        
</head>
    </head>
    <style>
        body{
            display: flex;
            margin: 10;
            justify-content: center;
            max-height: fit-content;
        }
        .sidebar{
            width: 18%;
            padding:25px;
            box-shadow: 10px 0 5px rgba(0,0,0,0.1);
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            height: 100vh;
            position: fixed;  
            top: 0;           
            left: 0;          
            overflow: hidden
        }
        .main-content{
            margin-left: 18%;
            margin-right: 2%;
            width: 82%;
            padding: 25px;
            display: flex;
            flex-direction: column;
            justify-content: flex-start;
            height: 100vh;
            overflow-y: auto;
            box-sizing: border-box;
        }
        .search-bar {
            display: flex;
            margin-bottom: 20px;
        }
        .top-section {
            flex: 1;
            padding-bottom: 20px;
            height: 50%;
        }
        .bottom-section {
            flex: 1;
            padding-top: 20px;
            border-top: 1px solid #ccc;
            height: 50%;
        }
        .table-responsive {
            height: calc(100% - 50px); 
            overflow-y: auto; 
}
    </style>
    <body>
        <div class="sidebar">
            <div>
                {% block side_bar_options %}
                <!-- block to present what options the sponsor/influencer needs for easy access -->
                {% endblock %}
            </div>
            {% if current_user.is_authenticated %}
            <button class="btn btn-secondary" onclick="window.location.href='{{ url_for('auth.logout') }}'">Logout</button>
        {% endif %}
        </div>
        <div class="main-content">
            {% block content %}
            <!-- Content specific to each page will go here -->

            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>


            {% endblock %}
        </div>
    </body>
</html>

website/templates/create_campaign.html
{% extends "sponsor_base.html" %}


{% block content %}
    <div class="campaign-container">
    <form method="POST" enctype="multipart/form-data" >
        <div class="form-group">
            <label for="campaign_name" class="form-label">Campaign Name:</label>
            <input type="text" class="form-control" id="campaign_name" name="campaign_name"required>
        </div>
        <div class="form-group">
            <label for="description" class="form-label">Description</label>
            <textarea type="text" class="form-control" id="description" name="description" required></textarea>
        </div>
        <div class="form-group">
            <label for="start_date" class="form-label">Start Date</label>
            <input type="date" class="form-control" id="start_date" name="start_date" required>
        </div>
        <div class="form-group">
            <label for="end_date" class="form-label">End Date</label>
            <input type="date" class="form-control" id="end_date" name="end_date" required>
        </div>
        <div class="form-group">
            <label for="budget" class="form-label">Budget</label>
            <input type="number" class="form-control" id="end_date" name="budget">
        </div>
        <div class="form-group">
            <label for="visibility" class="form-label">Visibility</label>
            <select name="visibility" id="visibility" class="form-select">
                <option value="Public" >Public</option>
                <option value="Private" >Private</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
    </div>
{% endblock %}

website/templates/edit_campaigns.html
{% extends "sponsor_base.html" %}


{% block content %}
    <h2>Edit your Campaigns</h2>
    <form method="post">
        <div class="form-group">
            <label for="campaign_name">Campaign Name</label>
            <input type="text" class="form-control" id="campaign_name" name="campaign_name" value="{{ campaign.campaign_name }}" required>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description" required>{{ campaign.description }}</textarea>
        </div>
        <div class="form-group">
            <label for="start_date">Start Date</label>
            <input type="date" class="form-control" id="start_date" name="start_date" value="{{ campaign.start_date }}" required>
        </div>
        <div class="form-group">
            <label for="end_date">End Date</label>
            <input type="date" class="form-control" id="end_date" name="end_date" value="{{ campaign.end_date }}" required>
        </div>
        <div class="form-group">
            <label for="budget">Budget</label>
            <input type="number" step="0.01" class="form-control" id="budget" name="budget" value="{{ campaign.budget }}" required>
        </div>
        <div class="form-group">
            <label for="visibility">Visibility</label>
            <select class="form-control" id="visibility" name="visibility" required>
                <option value="Public" {% if campaign.visibility == 'Public' %}selected{% endif %}>Public</option>
                <option value="Private" {% if campaign.visibility == 'Private' %}selected{% endif %}>Private</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Update Campaign</button>
    </form>
{% endblock %}

website/templates/edit_influ_profile.html
{% extends "influ_base.html" %}

{% block content %}
<br>
{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
{% for category, message in messages %}
    <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
{% endfor %}
{% endif %}
{% endwith %}
<br>

    <h3>Edit Your Profile</h3>
    <form method="POST" action="{{ url_for('views.edit_influ_profile', influencer_id=influencer.influencer_id) }}">
        <div class="form-group">
            <label for="category" class="form-label">Category:</label>
            <input type="text" class="form-control" id="category" name="category" value="{{ influencer.category  }}" placeholder="{{influencer.category}}" required>
        </div>
        <div class="form-group">
            <label for="niche" class="form-label">Niche:</label>
            <input type="text" class="form-control" id="niche" name="niche" value="{{ influencer.niche  }}"placeholder="{{influencer.niche}}" required>
        </div>
        <div class="form-group">
            <label for="reach">Reach</label>
            <input type="number" class="form-control" id="reach" name="reach" value="{{ influencer.reach  }}" placeholder="{{influencer.reach}}" required>
        </div>
        <button type="submit" class="btn btn-primary">Update Profile</button>
    </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

website/templates/influ_profile.html
{% extends "influ_base.html" %}

{% block content %}
       <form method="post", action="{{ url_for('views.edit_influ_profile',influencer_id=influencer.influencer_id) }}">
            <button type="submit" class="btn btn-secondary" >
                Edit your profile :)
            </button>

        </form>
        </button>
    <div class="container mt-5" style="display: flex; justify-content: space-between;">
        <div style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{influencer.name }}</h5>
                <p class="card-text"><strong>Mail: {{influencer.mail_id}}</strong></p>
                <p class="card-text"><strong>Category: {{influencer.category}}</strong></p>
                <p class="card-text"><strong>Niche: {{influencer.niche}}</strong></p>
                <p class="card-text"><strong>Reach: {{influencer.reach}}</strong></p>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-with, initail-scale=1">
        <title>Login Page</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        body{
            margin: 0;
            display: flex;
            background-color: #e4ed91;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .login-containter{
            background-color: rgb(240, 242, 245);
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
            width: 400px;
        }
        .login-containter input{
            width: 100%;
            padding: 10px;
            margin: 10px 0;
        }
    </style>
    </head>
    <body>
        <center>
        <div class="login-containter">
            <h3>Login to explore more</h3>
            <form method="POST" action="{{ url_for('auth.login') }}">
                <div class="form-group">
                    <input class="form-control" type="text" name="usrname" id="usrname" placeholder="Username" required>                   
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password" required>
                </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                    <br>
                    <p style="margin-top: 1rem;">New User?   <button class="btn btn-secondary" onclick="window.location.href='{{ url_for('auth.signup') }}'">SignUp</button>
                    </p>
            </form>
            <br>
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            <br>
        </div>
        </center>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

website/templates/my_campaigns.html
{% extends "sponsor_base.html" %}
{% block content %}

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Campaign Name</th>
                <th>Description</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Budget</th>
                <th>Visibility</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for campaign in campaigns %}
                <tr>
                    <td>{{ campaign.campaign_name }}</td>
                    <td>{{ campaign.description }}</td>
                    <td>{{ campaign.start_date }}</td>
                    <td>{{ campaign.end_date }}</td>
                    <td>{{ campaign.budget }}</td>
                    <td>{{ campaign.visibility }}</td>
                    <td>
                        <a href="{{ url_for('views.edit_campaign', campaign_id=campaign.campaign_id) }}" class="btn btn-warning btn-sm">Edit</a>
                        <form action="{{ url_for('views.delete_campaign', campaign_id=campaign.campaign_id) }}" method="post" style="display:inline;">
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="7">No Campaigns found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}